name: pythondatascientist
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - numpy
  - numpy-base
  - matplotlib
  - matplotlib-base
  - seaborn
  - folium
  - ffmpeg
  - geos
  - cartopy
  - pandas
  - pillow
  - python=3.8.5
  - scikit-image
  - scikit-learn
  - seaborn-base
