name: pythondatascientist
channels:
#  - conda-forge
  - default
dependencies:
  - mamba=0.7.10
  - python=3.7
  - folium=0.11.0
  - ffmpeg=4.3.1
  - geos=3.8.0
  - cartopy=0.18.0
  - pillow=8.0.1
  - matplotlib=3.3.2
  - numpy=1.19.2
  - pandas=1.1.5
  - pandas-datareader=0.9.0
  - pip=20.3.3
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - xlrd=2.0.1
