name: pythondatascientist
channels:
  - conda-forge
dependencies:
  - mamba
  - python=3.7
  - folium
  - ffmpeg
  - geos
  - cartopy
  - pillow
  - matplotlib
  - numpy
  - pandas
  - pandas-datareader
  - pip
  - pprofile
  - pyzmq
  - scikit-learn
  - scipy
  - seaborn
  - snakeviz
  - sympy
  - xlrd
